### ISSUE TITLE
"Kartan uppdaterad med OSM data från" uppdateras ej

### ISSUE THREAD

**Issue by kobbe** [skoterleder/skoterleder.org#10]
Trots att kartan uppdateras så ändras inte texten som säger när kartan uppdaterades senast:

Kartan uppdaterad med OSM data från: Fri Jan 15 2021 18:14:34 

![bild](https://user-images.githubusercontent.com/4288653/111354556-bd9f3780-8686-11eb-8380-7574e05826ee.png)

MVH Hans. Tack för en bra tjänst!

**Comment by rosangen** [comment]
Tack för informationen, jag har uppdaterat mitt script så nu borde datum uppdateras igen.

**Comment by kobbe** [comment]
Nu funkar det!
